# Generated by Django 4.2.16 on 2024-12-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habits_count_alter_habits_day_count"),
        ("statistic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "longest_streak",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Максимальное количество дней подряд, когда привычка была выполнена на 100%",
                        verbose_name="Самая длинная серия выполнения",
                    ),
                ),
                (
                    "days_completed_current_month",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество дней за текущий месяц, когда привычка была выполнена на 100%",
                        verbose_name="Дни выполнения за месяц",
                    ),
                ),
                (
                    "days_missed_current_month",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество дней за текущий месяц с прогрессом 0%",
                        verbose_name="Пропущенные дни за месяц",
                    ),
                ),
                (
                    "last_reset",
                    models.DateField(
                        auto_now_add=True,
                        verbose_name="Дата последнего сброса",
                    ),
                ),
                (
                    "habit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="habits.habits",
                    ),
                ),
            ],
        ),
    ]
