# Generated by Django 4.2.16 on 2024-12-15 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название уведомления",
                        max_length=20,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="активное уведомление",
                        verbose_name="активно",
                    ),
                ),
                (
                    "is_active_day",
                    models.BooleanField(
                        default=True,
                        help_text="активное уведомление на день",
                        verbose_name="активно",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="время уведомления с точностью до минут",
                        verbose_name="время уведомления",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="время создания уведомления",
                        null=True,
                        verbose_name="время",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="время последнего обновления",
                        null=True,
                        verbose_name="время обновления",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
            },
        ),
    ]
