# Generated by Django 4.2.16 on 2024-12-17 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="название уведомления",
                        max_length=20,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="активное уведомление",
                        verbose_name="активно",
                    ),
                ),
                (
                    "periodic_time",
                    models.CharField(
                        choices=[
                            ("5min", "5 минут"),
                            ("15min", "15 минут"),
                            ("30min", "30 минут"),
                            ("1hour", "1 час"),
                            ("3hours", "3 часа"),
                        ],
                        help_text="период отправки уведомления с точностью до минут",
                        max_length=10,
                        verbose_name="период отправки уведомления",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="время начала отправки уведомлений",
                        verbose_name="начало отправки уведомлений",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="время конца отправки уведомлений",
                        verbose_name="конец отправки уведомлений",
                    ),
                ),
                (
                    "start_server_time",
                    models.TimeField(
                        help_text="серверное время начала отправки уведомлений",
                        null=True,
                        verbose_name="начало отправки уведомлений",
                    ),
                ),
                (
                    "end_server_time",
                    models.TimeField(
                        help_text="серверное время конца отправки уведомлений",
                        null=True,
                        verbose_name="конец отправки уведомлений",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="время создания уведомления",
                        verbose_name="время",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="время последнего обновления",
                        verbose_name="время обновления",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_notification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "уведомление",
                "verbose_name_plural": "уведомления",
            },
        ),
    ]
