# Generated by Django 4.2.16 on 2024-12-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habits",
            name="count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="сколько раз нужно выполнить привычку за день",
                verbose_name="число выполнений",
            ),
        ),
        migrations.AlterField(
            model_name="habits",
            name="day_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="сколько раз была выполнена привычка за день",
                verbose_name="число выполнений в день",
            ),
        ),
    ]
