# Generated by Django 4.2.16 on 2024-12-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="attempts_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="счетчик входов"
            ),
        ),
    ]
