# Generated by Django 4.2.16 on 2024-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_attempts_count_user_block_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="телеграмм айди",
            ),
        ),
    ]
