# Generated by Django 4.2.16 on 2024-12-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_attempts_count"),
        ("users", "0003_alter_user_telegram_id"),
    ]

    operations = []
